# --------------------
# Common configuration
global:
  imageRegistry: ""
  imagePullSecrets: []
  storageClass: ""

nameOverride: ""
fullnameOverride: ""
clusterDomain: "cluster.local"

# --------------------
# Kafka 이미지 및 디버그 설정
image:
  registry: docker.io
  repository: bitnami/kafka
  tag: 4.0.0-debian-12-r7
  pullPolicy: IfNotPresent
  pullSecrets: []
debug: false

# --------------------
# StatefulSet 설정
replicaCount: 3
updateStrategy: RollingUpdate

# --------------------
# Logging 및 resources
resources: {}
heapOpts:
  -Xmx1024m
  -Xms1024m

# --------------------
# 인증과 보안 (SASL/SSL)
auth:
  enabled: false

# --------------------
# 리스너 설정
listeners:
  client:
    name: CLIENT
    port: 9092
    containerPort: 9092
    protocol: PLAINTEXT
  controller:
    name: CONTROLLER
    port: 9093
    containerPort: 9093
    protocol: PLAINTEXT
  interbroker:
    name: INTERNAL
    port: 9094
    containerPort: 9094
    protocol: PLAINTEXT

# --------------------
# 서비스 설정 (내부)
service:
  type: ClusterIP
  port: 9092
  annotations: {}

# --------------------
# 외부 접속 설정
externalAccess:
  enabled: false
  service:
    type: LoadBalancer  # 또는 NodePort
    port: 9094
    nodePort: []
    loadBalancerIP: ""
    annotations: {}
    domain: ""
  
# --------------------
# 스토리지
persistence:
  enabled: true
  storageClass: ""
  accessModes:
    - ReadWriteOnce
  size: 8Gi
  existingClaim: ""
  
# --------------------
# KRaft (ZooKeeper-free 모드) 설정
kraft:
  enabled: true
  clusterId: "Bf6n5pT9ToKBAQ2MJbqzlw"
  existingKraftSecret: ""
  controllerReplicas: 3